spring:
  application:
    name: ${SPRING_APPLICATION_NAME:gateway}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ${GATEWAY_DISCOVERY_ENABLED:true}
          lower-case-service-id: ${GATEWAY_LOWER_CASE_SERVICE_ID:true}

server:
  port: ${GATEWAY_SERVER_PORT:8000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_EXPOSURE_INCLUDE:health,info}
