spring:
  application:
    name: ${SPRING_APPLICATION_NAME:discovery}

server:
  port: ${DISCOVERY_SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:false}
  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:false}
